version: '3.9'

services:
  pwn-i-forgor:
    restart: always
    build:
      context: "./challenges/pwn/i-forgor"
      dockerfile: "./Dockerfile"
    ports:
      - "52760:1337"
    privileged: yes  
  crypto-mean-median-blank:
    restart: always
    build:
      context: "./challenges/crypto/mean-median-blank"
      dockerfile: "./Dockerfile"
    ports:
      - "19813:5000"
    read_only: yes
  re-go-for-it:
    restart: always
    build:
      context: "./challenges/re/go-for-it"
      dockerfile: "./Dockerfile"
    ports:
      - "16781:1337"
    privileged: yes
  pwn-interesting:
    restart: always
    build:
      context: "./challenges/pwn/interesting"
      dockerfile: "./Dockerfile"
    ports:
      - "46412:1337"
    privileged: yes
