version: '3.9'

services:
  pwn-i-forgor:
    restart: always
    build:
      context: "./challenges/pwn/i-forgor"
      dockerfile: "./Dockerfile"
    ports:
      - "52760:1337"
    privileged: true
  crypto-mean-median-blank:
    restart: always
    build:
      context: "./challenges/crypto/mean-median-blank"
      dockerfile: "./Dockerfile"
    ports:
      - "19813:5000"
    read_only: true
  re-go-for-it:
    restart: always
    build:
      context: "./challenges/re/go-for-it"
      dockerfile: "./Dockerfile"
    ports:
      - "16781:1337"
    privileged: true
  pwn-interesting:
    restart: always
    build:
      context: "./challenges/pwn/interesting"
      dockerfile: "./Dockerfile"
    ports:
      - "46412:1337"
    privileged: true
  web-image2text:
    restart: always
    build:
      context: "./challenges/web/image2text"
      dockerfile: "./Dockerfile"
    ports:
      - "1065:8080"
  web-pints:
    restart: always
    build:
      context: "./challenges/web/pints"
      dockerfile: "./Dockerfile"
    ports:
      - "29824:5000"
    read_only: true
  web-secret-email:
    restart: always
    build:
      context: "./challenges/web/secret-email"
      dockerfile: "./Dockerfile"
    environment:
      - CTF_EMAIL=${CTF_EMAIL}
      - CTF_EMAIL_PASSWORD=${CTF_EMAIL_PASSWORD}
    ports:
      - "6369:5000"
    read_only: true
